### ISSUE TITLE
what's the apm install name for this? 

### ISSUE THREAD

**Issue by filipgoc** [GhostText/GhostText-for-Atom#6]
Hi, 

I tried 

Filips-MacBook-Pro:various-md filipgoc$ apm install GhostText-for-Atom
Filips-MacBook-Pro:various-md filipgoc$ apm install GhostText

but in vain. 
Package not found. 

Thanks!

**Comment by bfred-it** [comment]
This has never been published to apm, the standard procedure is to load it from GitHub.

**Comment by filipgoc** [comment]
Ha. Thanks. 
There's a post on Atom.Discuss that claimed otherwise. 
https://discuss.atom.io/t/how-to-install-ghosttext-for-atom/38993

**Comment by rizkysyazuli** [comment]
in case anyone's wondering. to install this package from GitHub, do this:

    apm install https://github.com/GhostText/GhostText-for-Atom
